version: "1.0"

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: software
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  currency-converter:
    image: currency-converter:1.0.0
    ports:
      - "8080:8080"
    environment:
      URL: jdbc:postgresql://postgres:5432/software
    restart: always
    depends_on:
      - postgres